# Generated by Django 3.0.6 on 2022-05-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('date_of_birth', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField(max_length=10)),
                ('nationality', models.CharField(choices=[('INDIA', 'INDIA'), ('PAKISTAN', 'PAKISTAN'), ('BANGLADESH', 'BANGLADESH'), ('NEPAL', 'NEPAL')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
