# Generated by Django 3.0.6 on 2022-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
