# Generated by Django 3.0.6 on 2022-05-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220510_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='contact_number',
        ),
    ]
